---
include:
  - board: eyelash_sofle_left
    shield: nice_view_battery
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: eyelash_sofle_right
    shield: nice_view_battery
  - board: eyelash_sofle_left
    shield: settings_reset
  # - board: sofle_left
  #   shield: nice_view_adapter nice_view_battery   #updated entry
  #   artifact-name: sofle_left_nice_view
  # - board: sofle_right
  #   shield: nice_view_adapter nice_view_battery   #updated entry
  #   artifact-name: sofle_right_nice_view
